FROM ruby:2.7

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs

WORKDIR /site
COPY ../../Gemfile .
COPY ../../Gemfile.lock .
RUN bundle install

# Add a script to be executed every time the container starts.
COPY docker/ruby/entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]
EXPOSE 4000