domain: klaasie.github.io
url: https://www.klaas.frl

title: "Klaas Poortinga"
tagline: "Personal portfolio site"
description: "Welcome to my personal portfolio website."
author: "Klaas Poortinga"
logo: "/images/device-icons/ms-icon-310x310.png"

twitter:
  username: KlaasPoortinga
  card: summary

collections:
  category:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

jekyll-archives:
  enabled: [categories, tags]
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

gems: [jekyll-paginate]
paginate: 5
paginate_path: "/posts/page/:num"

exclude:
  - "*.config.js"
  - "package*.json"
  - "assets"
  - "node_modules"
  - "vendor"
