version: '3'
services:
  web:
    build:
      context: ./
      dockerfile: ./docker/ruby/Dockerfile
    environment:
      - JEKYLL_ENV=development
    ports:
      - "4000:4000"
    volumes:
      - ./:/site